name: 'Upload coverage reports'
on:
    push:
      branches:
        - actionCoverage
        - develop
        - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
      with:
      token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      files: build/customJacocoReportDir/test/jacocoTestReport.xml  # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      fail_ci_if_error: true # optional (default = false)
      verbose: true # optional (default = false)
